name: Check xcode completeness

on:
  push:
    paths:
    - 'source/**'
    - 'tests/**'
  pull_request:
    paths:
    - 'source/**'
    - 'tests/**'

jobs:
  check-xcode-completeness:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        # Microsoft Repos (for dotnet, azure-cli etc.) frequently cause issues (https://github.com/dotnet/core-setup/issues/7778#issuecomment-523518122), and we don't need them anyways
        for apt_file in `grep -lr packages.microsoft.com /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
        sudo apt-get update
        sudo apt-get install python3-pip
        sudo pip install pbxproj
    - name: Execute xcode completeness check
      run: |
        ./tests/tests/try_xcode_fix.sh
